#! /bin/bash

# Author: Zach Thompson
# Date Due: 2/7/22
# Description: Basic I/O commands

touch agent_smith

ln -s agent_smith me
ln -s agent_smith me_me
ln -s agent_smith me_too

chmod 600 agent_smith

ls -l > smith_list.txt

wc -l < smith_list.txt