#! /bin/bash

# Author: Zach Thompson
# Date Due: 2/21/22
# Description: Practicing wget

wget -nc https://raw.githubusercontent.com/zach-thompson/BIEN-4290/main/Labs/lab_1/thompsz_stats.cpp?token=GHSAT0AAAAAABTQC32B4IQRG7V7JWZF7T5IYUCQIQA

# cat thompsz_stats.cpp | grep "statSpace" > wget_practice_out
grep -m1 ".*::" thompsz_stats | sed 's/::.*//g' >> wget_practice_out.txt

echo -n "class name:" >> wget_practice_out.txt
# Determine the class of all functions, and add a line to the bottom of the same file
class_name=$(grep -m1 "::.*" thompsz_stats | sed 's/.*::.*:://g')
echo $class_name | sed 's/(.*//g' >> wget_practice_out.txt





