#! /bin/bash
# Author: Zach Thompson
# Date: 2/15/22
# Description: Performs histogram and correlation analysis on all files within desired folder

read -p "Which concentration level would you like to analyze? (00 or 05): " selection # reads input into $selection
touch EEG_DATA/selected_files.txt # create temp folder

cd EEG_DATA/ERP$selection/ # navigates to selected folder

for file in *.txt # for all .txt files in selected folder
    do cat $file >> /home/thompsz/BIEN-4290/Labs/lab_1/EEG_DATA/selected_files.txt # concatenate files into the temp file
done

cd .. # navigate back to ./EEG_DATA

cp selected_files.txt catted_input.dat # copy everything from selected_files into catted_input
rm selected_files.txt # removes temp folder

cd .. # navigate back to ./lab_1 

./run >> ./EEG_DATA/ERP"$selection"_histogram.txt # performs statistical analysis on catted_input.dat

echo "Data stored in ./lab_1/EEG_DATA"

for (( i=1;i<=59;i++ ))
do
    let next=$i+1
    if [[ $selection -eq 00 ]]
    then
        ./corr ERP$selection/ERP00$i.txt ERP$selection/ERP00$next.txt >> ./EEG_DATA/conc_corr_$selection.csv
    else
        echo "$selection.$i vs $selection.$next," >> ./EEG_DATA/conc_corr_$selection.csv
        ./corr ERP$selection/ERP05.$i.txt ERP$selection/ERP05.$next.txt >> ./EEG_DATA/conc_corr_$selection.csv
    fi
done