# Zach's Midterm makefile

CC = g++ 
SHELL = /bin/bash

mowin.o: mowin.cpp
	$(CC)  -o  $@

seememow.o: seememow.cpp
	 $(CC) -c seememow.o $@

thehob.o: thehob.cpp
	$(CC)  -o  $@

tthti.o: tthti.cpp
	 $(CC) -c tthti.o $@


clean:
	rm *.o
